# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: food-delivery-apikey
spec:
  name: Food Delivery Apikey
  policies:
    - BucketFullAccess
    - FunctionFullAccess
    - IdentityFullAccess
---
# BUCKET - Courier
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-courier-bucket
spec:
  title: Courier
  description: Order Couriers
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    name:
      type: string
      title: name
      description: name of the courier
      options:
        position: left
    current_orders:
      type: relation
      title: current_orders
      description: current_orders that courier is delivering
      relationType: onetomany
      options:
        position: bottom
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-order-bucket
    current_vehicle:
      type: relation
      relationType: onetoone
      title: current_vehicle
      description: current_vehicle that courier is using
      options:
        position: right
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-vehicle-bucket
  primary: name
  order: 99
  history: false
---
# BUCKET - User
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-user-bucket
spec:
  title: User
  description: Users
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    identity_id:
      type: string
      title: identity_id
      description: Identity id
      options:
        position: left
    name:
      type: string
      title: name
      description: Name of the user
      options:
        position: right
    surname:
      type: string
      title: surname
      description: Surname of the user
      options:
        position: bottom
    phone:
      type: string
      title: phone
      description: Phone number
      options:
        position: bottom
    email:
      type: string
      title: email
      description: Email of the user
      options:
        position: right
    profile_picture:
      type: storage
      title: profile_picture
      description: User profile picture
      options:
        position: bottom
    address:
      type: array
      title: address
      description: Description of the address input
      options:
        position: bottom
      items:
        title: Title of the items
        type: object
        properties:
          title:
            type: string
            title: title
            description: Description of the title input
            options:
              position: bottom
          country:
            type: string
            title: country
            description: Description of the country input
            options:
              position: bottom
          province:
            type: string
            title: province
            description: Description of the province input
            options:
              position: bottom
          district:
            type: string
            title: district
            description: Description of the district input
            options:
              position: bottom
          full_address:
            type: string
            title: full_address
            description: Description of the full_address input
            options:
              position: bottom
          phone:
            type: string
            title: phone
            description: Description of the phone input
            options:
              position: bottom
  primary: name
  order: 100
  history: false
---
# BUCKET - Order
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-order-bucket
spec:
  title: Order
  description: All orders
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    delivery_location:
      type: location
      title: delivery_location
      options:
        position: bottom
      locationType: Point
    user:
      type: relation
      title: user
      description: Owner of the order
      relationType: onetoone
      options:
        position: bottom
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-user-bucket
    courier:
      type: relation
      title: courier
      description: Courier of the order
      relationType: onetoone
      options:
        position: bottom
      dependent: false
      primary: current_vehicle
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-courier-bucket
    created_at:
      type: date
      title: created_at
      description: What time the order was created
      default: :created_at
      options:
        position: bottom
    status:
      type: string
      title: status
      description: Status of the order
      enum:
        - preparing
        - delivering
        - delivered
        - cancelled
      default: preparing
      options:
        position: bottom
    price:
      type: number
      title: price
      options:
        position: bottom
    payment_method:
      type: string
      title: payment_method
      description: Payment method of the order
      enum:
        - cash
        - credit_card
        - online
      options:
        position: bottom
    note:
      type: textarea
      title: note
      description: Note of the order
      options:
        position: bottom
    foods:
      type: array
      title: foods
      description: Description of the Foods input
      options:
        position: bottom
      items:
        title: Title of the items
        type: object
        properties:
          _id:
            type: string
            title: _id
            description: Description of the _id input
            options:
              position: bottom
          name:
            type: string
            title: name
            description: Description of the name input
            options:
              position: bottom
          ingredients:
            type: array
            title: ingredients
            description: Description of the ingredients input
            options:
              position: bottom
            items:
              title: Title of the items
              type: string
          price:
            type: number
            title: price
            description: Description of the price input
            options:
              position: bottom
          count:
            type: number
            title: count
            description: Description of the count input
            options:
              position: bottom
            minimum: 1
    address:
      type: object
      title: address
      description: Description of the address input
      options:
        position: bottom
        properties:
          title:
            type: string
            title: title
            description: Description of the title input
            options:
              position: bottom
          country:
            type: string
            title: country
            description: Description of the country input
            options:
              position: bottom
          province:
            type: string
            title: province
            description: Description of the province input
            options:
              position: bottom
          district:
            type: string
            title: district
            description: Description of the district input
            options:
              position: bottom
          full_address:
            type: string
            title: full_address
            description: Description of the full_address input
            options:
              position: bottom
          phone:
            type: string
            title: phone
            description: Description of the phone input
            options:
              position: bottom
    rating:
      type: relation
      title: rating
      description: Description of the rating input
      relationType: onetoone
      options:
        position: left
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-rating-bucket
  primary: note
  order: 101
  history: false
---
# BUCKET - Vehicle
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-vehicle-bucket
spec:
  title: Vehicle
  description: Delivery vehicles
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    name:
      type: string
      title: name
      description: Name of the vehicle
      options:
        position: left
  primary: name
  order: 102
  history: false
---
# BUCKET - Ingredient
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-ingredient-bucket
spec:
  title: Ingredient
  description: Food Ingredients
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    name:
      type: string
      title: name
      description: Name of the ingredient
      options:
        position: left
    price:
      type: number
      title: price
      description: $
      minimum: 0
      options:
        position: right
    stock:
      type: number
      title: stock
      description: Stock status of the ingredient
      minimum: 0
      options:
        position: left
    unit:
      type: string
      title: unit
      description: Unit of the stock
      options:
        position: right
    calories:
      type: number
      title: calories
      options:
        position: left
  primary: name
  order: 103
  history: false
---
# BUCKET - Rating
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-rating-bucket
spec:
  title: Rating
  description: Food Ratings
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    user:
      type: relation
      title: user
      description: User of the rating
      relationType: onetoone
      options:
        position: left
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-user-bucket
    rating:
      type: number
      title: rating
      description: Rating from 1 to 5
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      options:
        position: right
    comment:
      type: textarea
      title: comment
      description: Comment of the rating
      options:
        position: bottom
  primary: comment
  order: 104
  history: false
---
# BUCKET - Food
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-food-bucket
spec:
  title: Food
  description: Foods
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    name:
      type: string
      title: name
      description: Food name
      options:
        position: left
    categories:
      type: relation
      title: categories
      description: Food categories
      relationType: onetomany
      options:
        position: right
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-category-bucket
    description:
      type: textarea
      title: description
      description: Description of the food
      options:
        position: right
    image:
      type: storage
      title: image
      options:
        position: bottom
    original_price:
      type: number
      title: original_price
      description: $
      minimum: 0
      options:
        position: right
    is_available:
      type: boolean
      title: is_available
      description: Whether the food is available to prepare
      default: true
      options:
        position: bottom
    ratings:
      type: relation
      title: ratings
      description: Ratings of the food
      relationType: onetomany
      dependent: true
      options:
        position: bottom
      primary: comment
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-rating-bucket
    preparation_time:
      type: number
      title: preparation_time
      description: Estimated preparation time in minutes
      minimum: 0
      options:
        position: bottom
    extra_ingredients:
      type: relation
      title: extra_ingredients
      description: Description of the extra_ingredients input
      options:
        position: left
      relationType: onetomany
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-ingredient-bucket
    removable_ingredients:
      type: relation
      title: removable_ingredients
      description: Ingredients that can be removed from food
      options:
        position: left
      relationType: onetomany
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-ingredient-bucket
    calories:
      type: number
      title: calories
      description: Total calories of the food
      options:
        position: bottom
      minimum: 0
    ingredients:
      type: relation
      title: ingredients
      description: Description of the Ingredients input
      options:
        position: left
      relationType: onetomany
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-ingredient-bucket
    price:
      type: number
      title: price
      description: Description of the price input
      options:
        position: bottom
      minimum: 0
  primary: name
  order: 105
  history: false
---
# BUCKET - Discount
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-discount-bucket
spec:
  title: Discount
  description: Discounts
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    name:
      type: string
      title: name
      description: Name of the discount
      options:
        position: left
    foods:
      type: relation
      title: foods
      description: Which foods will be included to the discount
      relationType: onetomany
      options:
        position: bottom
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-food-bucket
    from:
      type: date
      title: from
      description: What time the discont will be started
      options:
        position: left
    until:
      type: date
      title: until
      description: What time the discont will be ended
      options:
        position: right
    discount:
      type: number
      title: discount
      description: Percentage of the discount
      minimum: 0
      maximum: 100
      options:
        position: right
  primary: discount
  order: 106
  history: false
---
# BUCKET - Category
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-category-bucket
spec:
  title: Category
  description: Food Categories
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    name:
      type: string
      title: name
      description: Name of the category
      options:
        position: left
  primary: name
  order: 107
  history: false
---
# BUCKET - Address
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-food-delivery-asset-address-bucket
spec:
  title: Address
  description: Addresses
  icon: fastfood
  acl:
    write: true==true
    read: true==true
  properties:
    title:
      type: string
      title: title
      description: Title of the address
      options:
        position: left
    location:
      type: location
      title: location
      options:
        position: right
      locationType: Point
  primary: location
  order: 108
  history: false
---
# FUNCTION - Food Delivery
apiVersion: function/v1
kind: Function
metadata:
  name: spica-food-delivery-asset-food-delivery-function
spec:
  description: All necessary methods for food delivery asset
  language: javascript
  timeout: 10
  environment:
    - name: FOOD_DELIVERY_APIKEY
      # we should put reference here
      valueFrom:
        resourceFieldRef:
          apiKeyName: food-delivery-apikey
    - name: DISCOUNT_BUCKET
      valueFrom:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-discount-bucket
  dependency: []
  title: Food Delivery
  code: ./function/spica-food-delivery-asset-food-delivery.js
  runtime:
    name: Node
    language: Javascript
---
# TRIGGER - onDiscountChange
apiVersion: function/v1
kind: Trigger
metadata:
  name: onDiscountChange
spec:
  active: true
  type: bucket
  name: onDiscountChange
  func: spica-food-delivery-asset-food-delivery-function
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: spica-food-delivery-asset-discount-bucket
    type: ALL
---
# TRIGGER - onTick
apiVersion: function/v1
kind: Trigger
metadata:
  name: onTick
spec:
  active: true
  type: schedule
  name: onTick
  func: spica-food-delivery-asset-food-delivery-function
  scheduleOptions:
    frequency: '* * * * *'
    timezone: Europe/Istanbul
---
# FUNCTION - Food Delivery Authorization
apiVersion: function/v1
kind: Function
metadata:
  name: spica-food-delivery-asset-authorization-function
spec:
  language: javascript
  timeout: 25
  description: Authorization process
  environment:
    - name: USER_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-food-delivery-asset-user-bucket
    - name: SECRET_API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: food-delivery-apikey
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
    - name: "@spica-devkit/identity"
      version: latest
  title: Food Delivery Authorization
  code: ./function/spica-food-delivery-asset-authorization-function.js
  runtime:
    name: Node
    language: Javascript
---
# TRIGGER - register
apiVersion: function/v1
kind: Trigger
metadata:
  name: register
spec:
  type: http
  active: true
  name: register
  func: spica-food-delivery-asset-authorization-function
  httpOptions:
    method: Post
    path: /register